<?php
	if($map_new_1 == "seoul") $map_new_1_kor = "서울";
	else if( $map_new_1 == "incheon") $map_new_1_kor = "인천";
	else if( $map_new_1 == "gyeonggi") $map_new_1_kor = "경기도";
	else if( $map_new_1 == "chungnam") $map_new_1_kor = "충청남도";
	else if( $map_new_1 == "chungbuk") $map_new_1_kor = "충청북도";
	else if( $map_new_1 == "daejeon") $map_new_1_kor = "대전";
	else if( $map_new_1 == "jeonbuk") $map_new_1_kor = "전라북도";
	else if( $map_new_1 == "gwangju") $map_new_1_kor = "광주";
	else if( $map_new_1 == "jeonnam") $map_new_1_kor = "전라남도";
	else if( $map_new_1 == "jeju") $map_new_1_kor = "제주도";
	else if( $map_new_1 == "gangwon") $map_new_1_kor = "강원도";
	else if( $map_new_1 == "gyeongbuk") $map_new_1_kor = "경상북도";
	else if( $map_new_1 == "daegu") $map_new_1_kor = "대구";
	else if( $map_new_1 == "gyeongnam") $map_new_1_kor = "경상남도";
	else if( $map_new_1 == "ulsan") $map_new_1_kor = "울산";
	else if( $map_new_1 == "busan") $map_new_1_kor = "부산";
	else if( $map_new_1 == "ulleung") $map_new_1_kor = "울릉도";
	else if( $map_new_1 == "dokdo") $map_new_1_kor = "독도";

	if($map_new_2 == "seoul") $map_new_2_kor = "서울";
	else if( $map_new_2 == "incheon") $map_new_2_kor = "인천";
	else if( $map_new_2 == "gyeonggi") $map_new_2_kor = "경기도";
	else if( $map_new_2 == "chungnam") $map_new_2_kor = "충청남도";
	else if( $map_new_2 == "chungbuk") $map_new_2_kor = "충청북도";
	else if( $map_new_2 == "daejeon") $map_new_2_kor = "대전";
	else if( $map_new_2 == "jeonbuk") $map_new_2_kor = "전라북도";
	else if( $map_new_2 == "gwangju") $map_new_2_kor = "광주";
	else if( $map_new_2 == "jeonnam") $map_new_2_kor = "전라남도";
	else if( $map_new_2 == "jeju") $map_new_2_kor = "제주도";
	else if( $map_new_2 == "gangwon") $map_new_2_kor = "강원도";
	else if( $map_new_2 == "gyeongbuk") $map_new_2_kor = "경상북도";
	else if( $map_new_2 == "daegu") $map_new_2_kor = "대구";
	else if( $map_new_2 == "gyeongnam") $map_new_2_kor = "경상남도";
	else if( $map_new_2 == "ulsan") $map_new_2_kor = "울산";
	else if( $map_new_2 == "busan") $map_new_2_kor = "부산";
	else if( $map_new_2 == "ulleung") $map_new_2_kor = "울릉도";
	else if( $map_new_2 == "dokdo") $map_new_2_kor = "독도";

	if($map_new_3 == "seoul") $map_new_3_kor = "서울";
	else if( $map_new_3 == "incheon") $map_new_3_kor = "인천";
	else if( $map_new_3 == "gyeonggi") $map_new_3_kor = "경기도";
	else if( $map_new_3 == "chungnam") $map_new_3_kor = "충청남도";
	else if( $map_new_3 == "chungbuk") $map_new_3_kor = "충청북도";
	else if( $map_new_3 == "daejeon") $map_new_3_kor = "대전";
	else if( $map_new_3 == "jeonbuk") $map_new_3_kor = "전라북도";
	else if( $map_new_3 == "gwangju") $map_new_3_kor = "광주";
	else if( $map_new_3 == "jeonnam") $map_new_3_kor = "전라남도";
	else if( $map_new_3 == "jeju") $map_new_3_kor = "제주도";
	else if( $map_new_3 == "gangwon") $map_new_3_kor = "강원도";
	else if( $map_new_3 == "gyeongbuk") $map_new_3_kor = "경상북도";
	else if( $map_new_3 == "daegu") $map_new_3_kor = "대구";
	else if( $map_new_3 == "gyeongnam") $map_new_3_kor = "경상남도";
	else if( $map_new_3 == "ulsan") $map_new_3_kor = "울산";
	else if( $map_new_3 == "busan") $map_new_3_kor = "부산";
	else if( $map_new_3 == "ulleung") $map_new_3_kor = "울릉도";
	else if( $map_new_3 == "dokdo") $map_new_3_kor = "독도";

	if($map_best_1 == "seoul") $map_best_1_kor = "서울";
	else if( $map_best_1 == "incheon") $map_best_1_kor = "인천";
	else if( $map_best_1 == "gyeonggi") $map_best_1_kor = "경기도";
	else if( $map_best_1 == "chungnam") $map_best_1_kor = "충청남도";
	else if( $map_best_1 == "chungbuk") $map_best_1_kor = "충청북도";
	else if( $map_best_1 == "daejeon") $map_best_1_kor = "대전";
	else if( $map_best_1 == "jeonbuk") $map_best_1_kor = "전라북도";
	else if( $map_best_1 == "gwangju") $map_best_1_kor = "광주";
	else if( $map_best_1 == "jeonnam") $map_best_1_kor = "전라남도";
	else if( $map_best_1 == "jeju") $map_best_1_kor = "제주도";
	else if( $map_best_1 == "gangwon") $map_best_1_kor = "강원도";
	else if( $map_best_1 == "gyeongbuk") $map_best_1_kor = "경상북도";
	else if( $map_best_1 == "daegu") $map_best_1_kor = "대구";
	else if( $map_best_1 == "gyeongnam") $map_best_1_kor = "경상남도";
	else if( $map_best_1 == "ulsan") $map_best_1_kor = "울산";
	else if( $map_best_1 == "busan") $map_best_1_kor = "부산";
	else if( $map_best_1 == "ulleung") $map_best_1_kor = "울릉도";
	else if( $map_best_1 == "dokdo") $map_best_1_kor = "독도";

	if($map_best_2 == "seoul") $map_best_2_kor = "서울";
	else if( $map_best_2 == "incheon") $map_best_2_kor = "인천";
	else if( $map_best_2 == "gyeonggi") $map_best_2_kor = "경기도";
	else if( $map_best_2 == "chungnam") $map_best_2_kor = "충청남도";
	else if( $map_best_2 == "chungbuk") $map_best_2_kor = "충청북도";
	else if( $map_best_2 == "daejeon") $map_best_2_kor = "대전";
	else if( $map_best_2 == "jeonbuk") $map_best_2_kor = "전라북도";
	else if( $map_best_2 == "gwangju") $map_best_2_kor = "광주";
	else if( $map_best_2 == "jeonnam") $map_best_2_kor = "전라남도";
	else if( $map_best_2 == "jeju") $map_best_2_kor = "제주도";
	else if( $map_best_2 == "gangwon") $map_best_2_kor = "강원도";
	else if( $map_best_2 == "gyeongbuk") $map_best_2_kor = "경상북도";
	else if( $map_best_2 == "daegu") $map_best_2_kor = "대구";
	else if( $map_best_2 == "gyeongnam") $map_best_2_kor = "경상남도";
	else if( $map_best_2 == "ulsan") $map_best_2_kor = "울산";
	else if( $map_best_2 == "busan") $map_best_2_kor = "부산";
	else if( $map_best_2 == "ulleung") $map_best_2_kor = "울릉도";
	else if( $map_best_2 == "dokdo") $map_best_2_kor = "독도";

	if($map_best_3 == "seoul") $map_best_3_kor = "서울";
	else if( $map_best_3 == "incheon") $map_best_3_kor = "인천";
	else if( $map_best_3 == "gyeonggi") $map_best_3_kor = "경기도";
	else if( $map_best_3 == "chungnam") $map_best_3_kor = "충청남도";
	else if( $map_best_3 == "chungbuk") $map_best_3_kor = "충청북도";
	else if( $map_best_3 == "daejeon") $map_best_3_kor = "대전";
	else if( $map_best_3 == "jeonbuk") $map_best_3_kor = "전라북도";
	else if( $map_best_3 == "gwangju") $map_best_3_kor = "광주";
	else if( $map_best_3 == "jeonnam") $map_best_3_kor = "전라남도";
	else if( $map_best_3 == "jeju") $map_best_3_kor = "제주도";
	else if( $map_best_3 == "gangwon") $map_best_3_kor = "강원도";
	else if( $map_best_3 == "gyeongbuk") $map_best_3_kor = "경상북도";
	else if( $map_best_3 == "daegu") $map_best_3_kor = "대구";
	else if( $map_best_3 == "gyeongnam") $map_best_3_kor = "경상남도";
	else if( $map_best_3 == "ulsan") $map_best_3_kor = "울산";
	else if( $map_best_3 == "busan") $map_best_3_kor = "부산";
	else if( $map_best_3 == "ulleung") $map_best_3_kor = "울릉도";
	else if( $map_best_3 == "dokdo") $map_best_3_kor = "독도";
?>